-- Tabla de parametros para tamanos de pagina del listado de socios
-- Requerimiento: opciones de select siempre provenientes de base de datos

create table if not exists public.member_page_sizes (
  id bigint generated by default as identity primary key,
  value integer not null unique check (value > 0),
  label text not null,
  sort_order integer not null default 0,
  activo boolean not null default true,
  created_at timestamp with time zone not null default now()
);

alter table public.member_page_sizes enable row level security;

drop policy if exists "member_page_sizes_select_authenticated" on public.member_page_sizes;
create policy "member_page_sizes_select_authenticated"
  on public.member_page_sizes
  for select
  to authenticated
  using (true);

insert into public.member_page_sizes (value, label, sort_order, activo)
values
  (5, '5 por pagina', 1, true),
  (10, '10 por pagina', 2, true),
  (25, '25 por pagina', 3, true),
  (50, '50 por pagina', 4, true)
on conflict (value)
do update set
  label = excluded.label,
  sort_order = excluded.sort_order,
  activo = excluded.activo;
